### ISSUE TITLE
Example app Error: Cannot find module './lib/server'

### ISSUE THREAD

**Issue by mitpaladin** [FormidableLabs/freactal#69]
Trying to test out the example app but `npm start` returns:

```
> test@0.1.0 start /Users/charlesdu/src/rails/freactal/example
> NODE_ENV=development babel-node ./src/server

module.js:472
    throw err;
    ^

Error: Cannot find module './lib/server'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/charlesdu/src/rails/freactal/server.js:1:18)
    at Module._compile (module.js:571:32)
    at loader (/Users/charlesdu/src/rails/freactal/example/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/charlesdu/src/rails/freactal/example/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```
seems it is looking to load a module `./lib/server` from ~/freactal/server.js but there is no /lib directory there?

**Comment by divmain** [comment]
You'll need to `npm run build` from the root to build `freactal`.  Then it can be imported by the `example` app (or anything else).
