### ISSUE TITLE
npm run check fails on local

### ISSUE THREAD

**Issue by Jascha-Sundaresan** [FormidableLabs/freactal#74]
I'm using node v6.11.0 and npm 3.10.10

Here is the console output:

```
> freactal@1.1.0 test /Users/XXX/freactal
> mocha spec/

/Users/XXX/freactal/spec/integration/nested-state-injection.spec.js:63
  it("children are updated when intermediate state injections are present", async function () {
                                                                            ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (/Users/XXX/freactal/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/XXX/freactal/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at fs.readdirSync.forEach.filename (/Users/XXX/freactal/spec/index.js:50:5)
    at Array.forEach (native)
    at recursiveRequire (/Users/XXX/freactal/spec/index.js:45:69)
    at Suite.describe (/Users/XXX/freactal/spec/index.js:48:30)
    at Object.create (/Users/XXX/freactal/node_modules/mocha/lib/interfaces/common.js:114:19)
    at context.describe.context.context (/Users/XXX/freactal/node_modules/mocha/lib/interfaces/bdd.js:44:27)
    at fs.readdirSync.forEach.filename (/Users/XXX/freactal/spec/index.js:48:5)
    at Array.forEach (native)
    at recursiveRequire (/Users/XXX/freactal/spec/index.js:45:69)
    at Object.<anonymous> (/Users/XXX/freactal/spec/index.js:54:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/XXX/freactal/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/XXX/freactal/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/XXX/freactal/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/Users/XXX/freactal/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/XXX/.nvm/versions/node/v6.11.0/bin/node" "/Users/XXX/.nvm/versions/node/v6.11.0/bin/npm" "run" "test"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! freactal@1.1.0 test: `mocha spec/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freactal@1.1.0 test script 'mocha spec/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freactal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha spec/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freactal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freactal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXX/freactal/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/XXX/.nvm/versions/node/v6.11.0/bin/node" "/Users/XXX/.nvm/versions/node/v6.11.0/bin/npm" "run" "check"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! freactal@1.1.0 check: `npm run lint && npm run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freactal@1.1.0 check script 'npm run lint && npm run test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freactal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm run test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freactal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freactal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/XXX/freactal/npm-debug.log
```

**Comment by Jascha-Sundaresan** [comment]
Here's the contents of the npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/XXX/.nvm/versions/node/v6.11.0/bin/node',
1 verbose cli   '/Users/XXX/.nvm/versions/node/v6.11.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'check' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'precheck', 'check', 'postcheck' ]
5 info lifecycle freactal@1.1.0~precheck: freactal@1.1.0
6 silly lifecycle freactal@1.1.0~precheck: no script for precheck, continuing
7 info lifecycle freactal@1.1.0~check: freactal@1.1.0
8 verbose lifecycle freactal@1.1.0~check: unsafe-perm in lifecycle true
9 verbose lifecycle freactal@1.1.0~check: PATH: /Users/XXX/.nvm/versions/node/v6.11.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/XXX/freactal/node_modules/.bin:/Users/XXX/.rvm/gems/ruby-2.4.1@rails510/bin:/Users/XXX/.rvm/gems/ruby-2.4.1@global/bin:/Users/XXX/.rvm/rubies/ruby-2.4.1/bin:/opt/local/bin:/opt/local/sbin:/Users/XXX/.nvm/versions/node/v6.11.0/bin:/opt/chefdk/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/XXX/.rvm/bin
10 verbose lifecycle freactal@1.1.0~check: CWD: /Users/XXX/freactal
11 silly lifecycle freactal@1.1.0~check: Args: [ '-c', 'npm run lint && npm run test' ]
12 silly lifecycle freactal@1.1.0~check: Returned: code: 1  signal: null
13 info lifecycle freactal@1.1.0~check: Failed to exec check script
14 verbose stack Error: freactal@1.1.0 check: `npm run lint && npm run test`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/XXX/.nvm/versions/node/v6.11.0/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/XXX/.nvm/versions/node/v6.11.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid freactal@1.1.0
16 verbose cwd /Users/XXX/freactal
17 error Darwin 15.6.0
18 error argv "/Users/XXX/.nvm/versions/node/v6.11.0/bin/node" "/Users/XXX/.nvm/versions/node/v6.11.0/bin/npm" "run" "check"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error freactal@1.1.0 check: `npm run lint && npm run test`
22 error Exit status 1
23 error Failed at the freactal@1.1.0 check script 'npm run lint && npm run test'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the freactal package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run lint && npm run test
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs freactal
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls freactal
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by divmain** [comment]
This is by design, for now.  Node v8.x is required to run tests, so that we can use async/await without a complex build pipeline.
